resources:
  - name: git_repo
    type: GitRepo
    configuration:
      # SCM integration where the repository is located
      gitProvider: GitHub
      # Repository path, including org name/repo name
      path: MaharshiPatel/simple-java-maven-app                     # Update with your "git_user"/SwampUp2021
      branches:
        # Specifies which branches will trigger dependent steps
        include: main

  - name: mvn_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: Artifactory
      buildName:  'simple-java-maven-app'
      buildNumber: $run_number
      externalCI: Artifactory

pipelines:
  - name: mvn_example_pipeline
    steps:
      - name: mvn_build_step
        type: MvnBuild
        configuration:
          deployerSnapshotRepo: su201-libs-snapshot
          deployerReleaseRepo:  su201-libs-release
          sourceLocation: ./
          mvnCommand: clean install
          inputResources:
            - name: git_repo
          integrations:
            - name: Artifactory

      - name: publish_build
        type: PublishBuildInfo
        configuration:
          forceXrayScan: true              # optional
          failOnScan: false                 # default true
          inputSteps:
            - name: mvn_build_step
          outputResources:
            - name: mvn_build_info